### ISSUE TITLE
Build not succeeding

### ISSUE THREAD

**Issue by UtkarshVerma** [mongoose-os-apps/losant-mqtt#1]
When I pass the `mos build --arch esp32` command within the cloned repo, I get a gigantic error. It's so big that I can't even scroll back to read the whole thing.

This is the error I get:
https://pastebin.com/krbtHKdk

**Comment by cpq** [comment]
@anaptfox could you follow up please?

**Comment by UtkarshVerma** [comment]
Removing the pin definitions from `mos.yml` worked for me.
